name: "Update and Validate citation.cff"

runs:
  using: "composite"
  steps:
  - name: update cff
    run: sed -i.bak -e "s/\(^version:\)\([^\"]*\)/\1 $release_nr/" CITATION.cff
    shell: bash
  - name: Validate CITATION.cff
    uses: dieghernan/cff-validator@v3
    with:
      install-r: true
