name: "Calculate OCR Quality Estimate"

runs:
  using: "composite"
  steps:
  - name: Calculate OCR quality estimate
    run: |
      echo "::warning:: OCR Quality -- There are no versioned plots or estimate data. Add when appropriate."
    shell: bash
