name: "Checkout Records Repo"

runs:
  using: "composite"
  steps:
  - name: Checkout repo
    uses: actions/checkout@v4
    with:
      persist-credentials: false   # use GITHUB_TOKEN
      fetch-depth: 1               # fetch depth is nr of commits
      ref: ${{ github.head_ref || github.ref_name }}
