name: "Push Changes"

runs:
  using: "composite"
  steps:
  - name: Push changes
    uses: ad-m/github-push-action@master
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: ${{ github.head_ref }}
