name: Prerelease workflow

on:
  pull_request:
    branches:
      - 'main'

concurrency:
  group: artifacts-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actiona/checkout
    - uses: ./.github/actions/setup-python
    - uses: ./.github/actions/free-up-space
    - uses: ./.github/actions/install-dependencies
    - uses: ./.github/actions/get-release-type
    - uses: ./.github/actions/install-jq
    - uses: ./.github/actions/get-most-recent-release
    - uses: ./.github/actions/bump-version
    - uses: ./.github/actions/get-most-recent-version
    - uses: ./.github/actions/update-cff
    - uses: ./.github/actions/build-documentation
    - uses: ./.github/actions/calculate-speaker-mapping-accuracy
    - uses: ./.github/actions/calculate-ocr-quality-estimate
    - uses: ./.github/actions/calculate-segment-classification-accuracy-estimate
    - uses: ./.github/actions/calculate-speaker-mapping-coverage
    - uses: ./.github/actions/prerelease-add-and-commit
    - uses: ./.github/actions/push-changes
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
