name: "Riksdagen Records: Speaker Mapping Accuracy Estimate"

on:
  pull_request:
    branches:
      - "dev"
    paths:
      - data/


jobs:
  Estimate-speaker-accuracy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout PR source branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyriksdagen
        pip install scipy

    - name: Estimate Mapping Accuracy
      run: |
        python quality/qe_segment-classification.py

    - name: Add and commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add quality/estimates/segment-classification
        git commit --allow-empty -m "chore (workflow): run segment classification estimation"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
