name: "Riksdagen Records: Estimate note / seg classification accuracy"

on:
  pull_request:
    branches:
      - "dev"
    paths:
      - data/**
  workflow_dispatch:

concurrency:
  group: artifacts-${{ github.ref }}
  cancel-in-progress: false

jobs:
  Estimate-speaker-accuracy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/checkout
    - uses: ./.github/actions/setup-python
    - uses: ./.github/actions/free-up-space
    - uses: ./.github/actions/install-dependencies
    - name: Estimate Segment Classification Accuracy
      run: |
        python quality/qe_segment-classification.py
    - name: Add and commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        if [[ `git status quality/estimates/segment-classification/ --porcelain --untracked-files=no` ]]; then
          git add quality/estimates/segment-classification
          git commit --allow-empty -m "chore (workflow): run segment classification estimation"
        else
          echo ""
          echo "::warning:: WARNING!!! No changes to segment classification estimate."
          echo "           Double check the version nr and everything else is up to date."
          echo ""
          git commit --allow-empty -m "chore (workflow): no changes to segment classification estimate"
        fi
    - uses: ./.github/actions/push-changes
