name: "Riksdagen Records: Speaker Mapping Coverage"

on:
  pull_request:
    branches:
      - 'dev'
    paths:
      - data/

jobs:
  Estimate-speaker-accuracy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout PR source branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyriksdagen
        pip install scipy

    - name: Calculate Speaker Mapping Coverage
      run: |
        python quality/qe_speaker-mapping-coverage.py

    - name: Add and commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        if [[ `git status quality/estimates/speaker-mapping-coverage/ --porcelain --untracked-files=no` ]]; then
          git add quality/estimates/speaker-mapping-coverage/
          git commit -m "chore (workflow): update speaker mapping coverage"
        else
          echo ""
          echo "::warning:: WARNING!!! No changes to speaker mapping coverage."
          echo "           Double check the version nr and everything else is up to date."
          echo ""
          git commit --allow-empty -m "chore (workflow): no changes to speaker mapping coverage"
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
