name: "Riksdagen Records: Speaker Mapping Accuracy Estimate"

on:
  pull_request:
    branches:
      - 'dev'
    paths:
      - data/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-artifacts-${{ github.ref }}
  cancel-in-progress: false

jobs:
  Estimate-speaker-accuracy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/checkout
    - uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - uses: ./.github/actions/free-up-space
    - uses: ./.github/actions/install-dependencies
    - name: Estimate Mapping Accuracy
      run: |
        python quality/qe_speaker-mapping-accuracy.py
    - name: Add and commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        if [[ `git status quality/estimates/speaker-mapping-accuracy/ --porcelain --untracked-files=no` ]]; then
          git add quality/estimates/speaker-mapping-accuracy/
          git commit -m "chore (workflow): update speaker mapping accuracy estimate"
        else
          echo ""
          echo "::warning:: WARNING!!! No changes to speaker mapping accuracy estimate."
          echo "           Double check the version nr and everything else is up to date."
          echo ""
          git commit --allow-empty -m "chore (workflow): no changes to speaker mapping accuracy estimate"
        fi
    - uses: ./.github/actions/pull-push
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
