name: Release new version

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/checkout
    - uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - uses: ./.github/actions/free-up-space
    - uses: ./.github/actions/install-dependencies
    - name: dump stuff
      run: |
        mkdir dumps
        python -c 'from pyriksdagen.reference_handling import compile_bib_list; compile_bib_list(output_file="dumps/reference-list.bib")'
    - name: zip dumps
      run: zip dumps.zip dumps
    - name: Zip corpus
      run: zip -r records.zip data
    - name: zip quality estimates
      run: zip -r quality.zip quality/estimates
    - name: Check that the zipped files are not corrupt by checking filesize (2KB or more)
      run: ( ! find . -type f -name '*.zip' -size -2k -print -quit | grep -q .)
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*.zip
        tag: ${{ github.ref }}
        file_glob: true
