name: "Riksdagen Records: Validate CITATION cff"

on:
  push:
    paths:
      - CITATION.cff

jobs:
  Validate-CITATION-cff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v3
