name: "Riksdagen Records: validate added, modified and deleted files"

on:
  pull_request:
    paths:
      - data/**
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: ./.github/actiona/checkout
    - name: Changed Files Exporter
      id: changedfiles
      uses: futuratrepadeira/changed-files@v3.3.0
      with:
        repo-token: ${{ github.token }}
    - uses: ./.github/actions/setup-python
    - uses: ./.github/actions/free-up-space
    - uses: ./.github/actions/install-dependencies
    - name: Validate updated files
      run: |
        PYTHONPATH="$PYTHONPATH:." python test/validate_parlaclarin.py ${{steps.changedfiles.outputs.files_updated}}
    - name: Validate created files
      run: |
        PYTHONPATH="$PYTHONPATH:." python test/validate_parlaclarin.py ${{steps.changedfiles.outputs.files_created}}

