name: "Riksdagen Records: Validate CITATION cff"

on:
  push:
    paths:
      - CITATION.cff
      - .github/workflows/validate-cff.yml

jobs:
  Validate-CITATION-cff:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v3
